In [2]:
import numpy as np

In [3]:
#let's create the vector which is a part of a nd array
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [4]:
y = np.array([[1,2], [3, 4], [5,6]])
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
type(x)

numpy.ndarray

In [6]:
type(y)

numpy.ndarray

In [9]:
#shape gives dimension of an array (rows, columns)
y.shape

(3, 2)

In [11]:
#transposition


In [12]:
yt = y.transpose()
yt

array([[1, 3, 5],
       [2, 4, 6]])

In [14]:
#Mattrix addition
# similar values are added
# scalar values are broadcasted only if the first array has same nber
#of rows as the second one, and one has only one column
c = 4
z = c + x
z

array([5, 6, 7, 8])

In [15]:
#multiplication: dot product
#nber of columns of first matrix = nber of rows of 2nd
A = np.array([[1, 2], [3, 4], [5, 6]]) 
B = np.array([[2], [4]])
C = A.dot(B)
C

array([[10],
       [22],
       [34]])

In [ ]:
#Matrix multiplication is not commutative ( AB!=BA)